userName=root
password=vignesh
url=jdbc:mysql://localhost:3306/bankdb
driverClassName=com.mysql.cj.jdbc.Driver
addIndividual=insert into individual(account_no,first_name,last_name,middle_name,email,contact_no,password,gender,birth_date)values(?,?,?,?,?,?,?,?,?);
allIndividuals=select * from individual;